//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRatingSystemClient.MovieSystemServiceReferece {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/MovieRatingSystem.Model")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Student_BranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Student_CPIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Student_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Student_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Student_Branch {
            get {
                return this.Student_BranchField;
            }
            set {
                if ((object.ReferenceEquals(this.Student_BranchField, value) != true)) {
                    this.Student_BranchField = value;
                    this.RaisePropertyChanged("Student_Branch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Student_CPI {
            get {
                return this.Student_CPIField;
            }
            set {
                if ((this.Student_CPIField.Equals(value) != true)) {
                    this.Student_CPIField = value;
                    this.RaisePropertyChanged("Student_CPI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Student_Id {
            get {
                return this.Student_IdField;
            }
            set {
                if ((this.Student_IdField.Equals(value) != true)) {
                    this.Student_IdField = value;
                    this.RaisePropertyChanged("Student_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Student_Name {
            get {
                return this.Student_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Student_NameField, value) != true)) {
                    this.Student_NameField = value;
                    this.RaisePropertyChanged("Student_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUser", Namespace="http://schemas.datacontract.org/2004/07/MovieRatingSystem.Model")]
    [System.SerializableAttribute()]
    public partial class SystemUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Designation {
            get {
                return this.User_DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.User_DesignationField, value) != true)) {
                    this.User_DesignationField = value;
                    this.RaisePropertyChanged("User_Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Name {
            get {
                return this.User_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_NameField, value) != true)) {
                    this.User_NameField = value;
                    this.RaisePropertyChanged("User_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Password {
            get {
                return this.User_PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.User_PasswordField, value) != true)) {
                    this.User_PasswordField = value;
                    this.RaisePropertyChanged("User_Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User_Rating", Namespace="http://schemas.datacontract.org/2004/07/MovieRatingSystem.Model")]
    [System.SerializableAttribute()]
    public partial class User_Rating : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MovieRatingSystemClient.MovieSystemServiceReferece.SystemUser SystemUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double User_Provided_RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_Rarting_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieName {
            get {
                return this.MovieNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieNameField, value) != true)) {
                    this.MovieNameField = value;
                    this.RaisePropertyChanged("MovieName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MovieRatingSystemClient.MovieSystemServiceReferece.SystemUser SystemUser {
            get {
                return this.SystemUserField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemUserField, value) != true)) {
                    this.SystemUserField = value;
                    this.RaisePropertyChanged("SystemUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double User_Provided_Rating {
            get {
                return this.User_Provided_RatingField;
            }
            set {
                if ((this.User_Provided_RatingField.Equals(value) != true)) {
                    this.User_Provided_RatingField = value;
                    this.RaisePropertyChanged("User_Provided_Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Rarting_Id {
            get {
                return this.User_Rarting_IdField;
            }
            set {
                if ((this.User_Rarting_IdField.Equals(value) != true)) {
                    this.User_Rarting_IdField = value;
                    this.RaisePropertyChanged("User_Rarting_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RatinDto", Namespace="http://schemas.datacontract.org/2004/07/MovieRatingSystem.Model")]
    [System.SerializableAttribute()]
    public partial class RatinDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double User_Provided_RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_Rarting_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieName {
            get {
                return this.MovieNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieNameField, value) != true)) {
                    this.MovieNameField = value;
                    this.RaisePropertyChanged("MovieName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double User_Provided_Rating {
            get {
                return this.User_Provided_RatingField;
            }
            set {
                if ((this.User_Provided_RatingField.Equals(value) != true)) {
                    this.User_Provided_RatingField = value;
                    this.RaisePropertyChanged("User_Provided_Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Rarting_Id {
            get {
                return this.User_Rarting_IdField;
            }
            set {
                if ((this.User_Rarting_IdField.Equals(value) != true)) {
                    this.User_Rarting_IdField = value;
                    this.RaisePropertyChanged("User_Rarting_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RatinDto2", Namespace="http://schemas.datacontract.org/2004/07/MovieRatingSystem.Model")]
    [System.SerializableAttribute()]
    public partial class RatinDto2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double User_Provided_RatingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieName {
            get {
                return this.MovieNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieNameField, value) != true)) {
                    this.MovieNameField = value;
                    this.RaisePropertyChanged("MovieName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double User_Provided_Rating {
            get {
                return this.User_Provided_RatingField;
            }
            set {
                if ((this.User_Provided_RatingField.Equals(value) != true)) {
                    this.User_Provided_RatingField = value;
                    this.RaisePropertyChanged("User_Provided_Rating");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RatinDto3", Namespace="http://schemas.datacontract.org/2004/07/MovieRatingSystem.Model")]
    [System.SerializableAttribute()]
    public partial class RatinDto3 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double User_Provided_RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_Rarting_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieName {
            get {
                return this.MovieNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieNameField, value) != true)) {
                    this.MovieNameField = value;
                    this.RaisePropertyChanged("MovieName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double User_Provided_Rating {
            get {
                return this.User_Provided_RatingField;
            }
            set {
                if ((this.User_Provided_RatingField.Equals(value) != true)) {
                    this.User_Provided_RatingField = value;
                    this.RaisePropertyChanged("User_Provided_Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Rarting_Id {
            get {
                return this.User_Rarting_IdField;
            }
            set {
                if ((this.User_Rarting_IdField.Equals(value) != true)) {
                    this.User_Rarting_IdField = value;
                    this.RaisePropertyChanged("User_Rarting_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovieSystemServiceReferece.IMovieSystem")]
    public interface IMovieSystem {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/AddMovie", ReplyAction="http://tempuri.org/IMovieSystem/AddMovieResponse")]
        string AddMovie(MovieRatingSystemClient.MovieSystemServiceReferece.Student e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/AddMovie", ReplyAction="http://tempuri.org/IMovieSystem/AddMovieResponse")]
        System.Threading.Tasks.Task<string> AddMovieAsync(MovieRatingSystemClient.MovieSystemServiceReferece.Student e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/UpdateMovie", ReplyAction="http://tempuri.org/IMovieSystem/UpdateMovieResponse")]
        string UpdateMovie(int id, MovieRatingSystemClient.MovieSystemServiceReferece.Student e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/UpdateMovie", ReplyAction="http://tempuri.org/IMovieSystem/UpdateMovieResponse")]
        System.Threading.Tasks.Task<string> UpdateMovieAsync(int id, MovieRatingSystemClient.MovieSystemServiceReferece.Student e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/DeleteMovie", ReplyAction="http://tempuri.org/IMovieSystem/DeleteMovieResponse")]
        string DeleteMovie(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/DeleteMovie", ReplyAction="http://tempuri.org/IMovieSystem/DeleteMovieResponse")]
        System.Threading.Tasks.Task<string> DeleteMovieAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/ShowMovie", ReplyAction="http://tempuri.org/IMovieSystem/ShowMovieResponse")]
        MovieRatingSystemClient.MovieSystemServiceReferece.Student[] ShowMovie();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/ShowMovie", ReplyAction="http://tempuri.org/IMovieSystem/ShowMovieResponse")]
        System.Threading.Tasks.Task<MovieRatingSystemClient.MovieSystemServiceReferece.Student[]> ShowMovieAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/AddUser", ReplyAction="http://tempuri.org/IMovieSystem/AddUserResponse")]
        string AddUser(MovieRatingSystemClient.MovieSystemServiceReferece.SystemUser s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/AddUser", ReplyAction="http://tempuri.org/IMovieSystem/AddUserResponse")]
        System.Threading.Tasks.Task<string> AddUserAsync(MovieRatingSystemClient.MovieSystemServiceReferece.SystemUser s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/DeleteUser", ReplyAction="http://tempuri.org/IMovieSystem/DeleteUserResponse")]
        string DeleteUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/DeleteUser", ReplyAction="http://tempuri.org/IMovieSystem/DeleteUserResponse")]
        System.Threading.Tasks.Task<string> DeleteUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/UpdateUser", ReplyAction="http://tempuri.org/IMovieSystem/UpdateUserResponse")]
        string UpdateUser(int id, MovieRatingSystemClient.MovieSystemServiceReferece.SystemUser e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/UpdateUser", ReplyAction="http://tempuri.org/IMovieSystem/UpdateUserResponse")]
        System.Threading.Tasks.Task<string> UpdateUserAsync(int id, MovieRatingSystemClient.MovieSystemServiceReferece.SystemUser e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/ShowUser", ReplyAction="http://tempuri.org/IMovieSystem/ShowUserResponse")]
        MovieRatingSystemClient.MovieSystemServiceReferece.SystemUser[] ShowUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/ShowUser", ReplyAction="http://tempuri.org/IMovieSystem/ShowUserResponse")]
        System.Threading.Tasks.Task<MovieRatingSystemClient.MovieSystemServiceReferece.SystemUser[]> ShowUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/Verify_User", ReplyAction="http://tempuri.org/IMovieSystem/Verify_UserResponse")]
        string Verify_User(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/Verify_User", ReplyAction="http://tempuri.org/IMovieSystem/Verify_UserResponse")]
        System.Threading.Tasks.Task<string> Verify_UserAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/AddRating", ReplyAction="http://tempuri.org/IMovieSystem/AddRatingResponse")]
        string AddRating(MovieRatingSystemClient.MovieSystemServiceReferece.User_Rating s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/AddRating", ReplyAction="http://tempuri.org/IMovieSystem/AddRatingResponse")]
        System.Threading.Tasks.Task<string> AddRatingAsync(MovieRatingSystemClient.MovieSystemServiceReferece.User_Rating s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/DeleteRating", ReplyAction="http://tempuri.org/IMovieSystem/DeleteRatingResponse")]
        string DeleteRating(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/DeleteRating", ReplyAction="http://tempuri.org/IMovieSystem/DeleteRatingResponse")]
        System.Threading.Tasks.Task<string> DeleteRatingAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/UpdateRating", ReplyAction="http://tempuri.org/IMovieSystem/UpdateRatingResponse")]
        string UpdateRating(int id, MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/UpdateRating", ReplyAction="http://tempuri.org/IMovieSystem/UpdateRatingResponse")]
        System.Threading.Tasks.Task<string> UpdateRatingAsync(int id, MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/ShowRating", ReplyAction="http://tempuri.org/IMovieSystem/ShowRatingResponse")]
        MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto[] ShowRating();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/ShowRating", ReplyAction="http://tempuri.org/IMovieSystem/ShowRatingResponse")]
        System.Threading.Tasks.Task<MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto[]> ShowRatingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/ShowRating_short", ReplyAction="http://tempuri.org/IMovieSystem/ShowRating_shortResponse")]
        MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto2[] ShowRating_short();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/ShowRating_short", ReplyAction="http://tempuri.org/IMovieSystem/ShowRating_shortResponse")]
        System.Threading.Tasks.Task<MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto2[]> ShowRating_shortAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/ShowRating_Persional", ReplyAction="http://tempuri.org/IMovieSystem/ShowRating_PersionalResponse")]
        MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto2[] ShowRating_Persional(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/ShowRating_Persional", ReplyAction="http://tempuri.org/IMovieSystem/ShowRating_PersionalResponse")]
        System.Threading.Tasks.Task<MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto2[]> ShowRating_PersionalAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/ShowRating_Log", ReplyAction="http://tempuri.org/IMovieSystem/ShowRating_LogResponse")]
        MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto3[] ShowRating_Log(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/ShowRating_Log", ReplyAction="http://tempuri.org/IMovieSystem/ShowRating_LogResponse")]
        System.Threading.Tasks.Task<MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto3[]> ShowRating_LogAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/getMovie_Name", ReplyAction="http://tempuri.org/IMovieSystem/getMovie_NameResponse")]
        string[] getMovie_Name();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieSystem/getMovie_Name", ReplyAction="http://tempuri.org/IMovieSystem/getMovie_NameResponse")]
        System.Threading.Tasks.Task<string[]> getMovie_NameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMovieSystemChannel : MovieRatingSystemClient.MovieSystemServiceReferece.IMovieSystem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovieSystemClient : System.ServiceModel.ClientBase<MovieRatingSystemClient.MovieSystemServiceReferece.IMovieSystem>, MovieRatingSystemClient.MovieSystemServiceReferece.IMovieSystem {
        
        public MovieSystemClient() {
        }
        
        public MovieSystemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovieSystemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieSystemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieSystemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddMovie(MovieRatingSystemClient.MovieSystemServiceReferece.Student e) {
            return base.Channel.AddMovie(e);
        }
        
        public System.Threading.Tasks.Task<string> AddMovieAsync(MovieRatingSystemClient.MovieSystemServiceReferece.Student e) {
            return base.Channel.AddMovieAsync(e);
        }
        
        public string UpdateMovie(int id, MovieRatingSystemClient.MovieSystemServiceReferece.Student e) {
            return base.Channel.UpdateMovie(id, e);
        }
        
        public System.Threading.Tasks.Task<string> UpdateMovieAsync(int id, MovieRatingSystemClient.MovieSystemServiceReferece.Student e) {
            return base.Channel.UpdateMovieAsync(id, e);
        }
        
        public string DeleteMovie(int id) {
            return base.Channel.DeleteMovie(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteMovieAsync(int id) {
            return base.Channel.DeleteMovieAsync(id);
        }
        
        public MovieRatingSystemClient.MovieSystemServiceReferece.Student[] ShowMovie() {
            return base.Channel.ShowMovie();
        }
        
        public System.Threading.Tasks.Task<MovieRatingSystemClient.MovieSystemServiceReferece.Student[]> ShowMovieAsync() {
            return base.Channel.ShowMovieAsync();
        }
        
        public string AddUser(MovieRatingSystemClient.MovieSystemServiceReferece.SystemUser s) {
            return base.Channel.AddUser(s);
        }
        
        public System.Threading.Tasks.Task<string> AddUserAsync(MovieRatingSystemClient.MovieSystemServiceReferece.SystemUser s) {
            return base.Channel.AddUserAsync(s);
        }
        
        public string DeleteUser(int id) {
            return base.Channel.DeleteUser(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserAsync(int id) {
            return base.Channel.DeleteUserAsync(id);
        }
        
        public string UpdateUser(int id, MovieRatingSystemClient.MovieSystemServiceReferece.SystemUser e) {
            return base.Channel.UpdateUser(id, e);
        }
        
        public System.Threading.Tasks.Task<string> UpdateUserAsync(int id, MovieRatingSystemClient.MovieSystemServiceReferece.SystemUser e) {
            return base.Channel.UpdateUserAsync(id, e);
        }
        
        public MovieRatingSystemClient.MovieSystemServiceReferece.SystemUser[] ShowUser() {
            return base.Channel.ShowUser();
        }
        
        public System.Threading.Tasks.Task<MovieRatingSystemClient.MovieSystemServiceReferece.SystemUser[]> ShowUserAsync() {
            return base.Channel.ShowUserAsync();
        }
        
        public string Verify_User(string user, string pass) {
            return base.Channel.Verify_User(user, pass);
        }
        
        public System.Threading.Tasks.Task<string> Verify_UserAsync(string user, string pass) {
            return base.Channel.Verify_UserAsync(user, pass);
        }
        
        public string AddRating(MovieRatingSystemClient.MovieSystemServiceReferece.User_Rating s) {
            return base.Channel.AddRating(s);
        }
        
        public System.Threading.Tasks.Task<string> AddRatingAsync(MovieRatingSystemClient.MovieSystemServiceReferece.User_Rating s) {
            return base.Channel.AddRatingAsync(s);
        }
        
        public string DeleteRating(int id) {
            return base.Channel.DeleteRating(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteRatingAsync(int id) {
            return base.Channel.DeleteRatingAsync(id);
        }
        
        public string UpdateRating(int id, MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto e) {
            return base.Channel.UpdateRating(id, e);
        }
        
        public System.Threading.Tasks.Task<string> UpdateRatingAsync(int id, MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto e) {
            return base.Channel.UpdateRatingAsync(id, e);
        }
        
        public MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto[] ShowRating() {
            return base.Channel.ShowRating();
        }
        
        public System.Threading.Tasks.Task<MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto[]> ShowRatingAsync() {
            return base.Channel.ShowRatingAsync();
        }
        
        public MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto2[] ShowRating_short() {
            return base.Channel.ShowRating_short();
        }
        
        public System.Threading.Tasks.Task<MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto2[]> ShowRating_shortAsync() {
            return base.Channel.ShowRating_shortAsync();
        }
        
        public MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto2[] ShowRating_Persional(int id) {
            return base.Channel.ShowRating_Persional(id);
        }
        
        public System.Threading.Tasks.Task<MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto2[]> ShowRating_PersionalAsync(int id) {
            return base.Channel.ShowRating_PersionalAsync(id);
        }
        
        public MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto3[] ShowRating_Log(int id) {
            return base.Channel.ShowRating_Log(id);
        }
        
        public System.Threading.Tasks.Task<MovieRatingSystemClient.MovieSystemServiceReferece.RatinDto3[]> ShowRating_LogAsync(int id) {
            return base.Channel.ShowRating_LogAsync(id);
        }
        
        public string[] getMovie_Name() {
            return base.Channel.getMovie_Name();
        }
        
        public System.Threading.Tasks.Task<string[]> getMovie_NameAsync() {
            return base.Channel.getMovie_NameAsync();
        }
    }
}
